### ISSUE TITLE
Error in connection of mongo db

### ISSUE THREAD

**Issue by matheusriios** [lcnetdev/recto#29]
When I try to start the recto, I get the following error:

```
/app/node_modules/mongodb/lib/utils.js:671
          throw error;
          ^

MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/app/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:316:20)
    at /app/node_modules/mongodb/lib/core/connection/pool.js:562:14
    at /app/node_modules/mongodb/lib/core/connection/pool.js:995:11
    at /app/node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/app/node_modules/mongodb/lib/core/connection/connect.js:280:5)
    at Socket.<anonymous> (/app/node_modules/mongodb/lib/core/connection/connect.js:310:7)
    at Object.onceWrapper (events.js:423:26)
    at Socket.emit (events.js:316:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'MongoNetworkError'
}
```

But, my connection uri is correct. On the verso, it works very well

**Comment by kefo** [comment]
Hi @matheusriios - I updated the documentation today.  Recto no longer uses Verso, which is part of the problem you were experiencing.  I suspect there is more I can do with the documentation so let me know.

**Comment by matheusriios** [comment]
@kefo - Now I'm having this problem:

Command: npm install

Error: 
```
npm WARN tar ENOENT: no such file or directory, open '/app/node_modules/.staging/es-abstract-a71e447d/2020/DeletePropertyOrThrow.js'
npm WARN The package supertest is included as both a dev and production dependency.

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/lcnetdev/ldpjs.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-30T13_25_39_217Z-debug.log
```
